/* ============================================================================
 * Online Reports state proxy — keeps the JSONBin master key off the client.
 *
 * One JSONBin bin per region (35 bins total). The bin holds the full
 * customisation state for that region: text overlays, shapes, images,
 * page backgrounds, page order, custom pages, page labels, bands.
 *
 *   GET  /.netlify/functions/reports-state?region=<slug>
 *        → latest state for that region (public read; viewers see overlays)
 *   PUT  /.netlify/functions/reports-state?region=<slug>
 *        → overwrite the region's state (Authorization: Bearer <token>)
 *
 * Env vars (set in Netlify → Site settings → Environment variables):
 *   JSONBIN_MASTER_KEY     The JSONBin master key (never exposed to the
 *                           browser). Same key the clock-state function
 *                           uses — one master key, multiple bins.
 *   JSONBIN_REPORTS_BINS   JSON object mapping region slug → bin ID.
 *                           e.g. {"sydney":"abc...","melbourne":"def...",...}
 *                           Generated by scripts/setup-reports-bins.mjs.
 *   REPORTS_WRITE_SECRET   Random string; must match the token the
 *                           tool sends in "Authorization: Bearer <token>"
 *                           on PUT. Internal-tool barrier (visible in
 *                           page source) — relies on the hub's tier
 *                           gating for actual access control.
 *
 * Node 18+ provides a built-in fetch, so no dependencies are required.
 * ========================================================================== */

const MASTER_KEY   = process.env.JSONBIN_MASTER_KEY;
const BINS_JSON    = process.env.JSONBIN_REPORTS_BINS;
const WRITE_SECRET = process.env.REPORTS_WRITE_SECRET;

const JSON_HEADERS = {
  "Content-Type": "application/json",
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, PUT, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization",
  "Cache-Control": "no-store",
};

function reply(statusCode, payload) {
  return { statusCode, headers: JSON_HEADERS, body: JSON.stringify(payload) };
}

let _binMap = null;
function binMap() {
  if (_binMap) return _binMap;
  try { _binMap = BINS_JSON ? JSON.parse(BINS_JSON) : {}; }
  catch { _binMap = {}; }
  return _binMap;
}

exports.handler = async (event) => {
  if (event.httpMethod === "OPTIONS") {
    return { statusCode: 204, headers: JSON_HEADERS, body: "" };
  }

  if (!MASTER_KEY) {
    return reply(500, { error: "Server misconfigured: JSONBIN_MASTER_KEY env var is missing." });
  }
  if (!BINS_JSON) {
    return reply(500, { error: "Server misconfigured: JSONBIN_REPORTS_BINS env var is missing. Run scripts/setup-reports-bins.mjs and paste its output." });
  }

  const slug = (event.queryStringParameters || {}).region;
  if (!slug) {
    return reply(400, { error: "Missing ?region=<slug> query parameter" });
  }
  const binId = binMap()[slug];
  if (!binId) {
    return reply(404, { error: "No bin configured for region: " + slug + ". Add it to JSONBIN_REPORTS_BINS." });
  }

  const binUrl = "https://api.jsonbin.io/v3/b/" + binId;

  if (event.httpMethod === "GET") {
    try {
      const res = await fetch(binUrl + "/latest", {
        headers: { "X-Master-Key": MASTER_KEY },
      });
      const body = await res.text();
      return { statusCode: res.status, headers: JSON_HEADERS, body };
    } catch (e) {
      return reply(502, { error: "Upstream GET failed", detail: String(e && e.message || e) });
    }
  }

  if (event.httpMethod === "PUT") {
    if (!WRITE_SECRET) {
      return reply(503, { error: "Writes disabled: REPORTS_WRITE_SECRET env var is not set." });
    }
    const auth = event.headers.authorization || event.headers.Authorization || "";
    const token = auth.replace(/^Bearer\s+/i, "").trim();
    if (token !== WRITE_SECRET) {
      return reply(401, { error: "Unauthorized" });
    }
    if (!event.body) {
      return reply(400, { error: "Missing request body" });
    }
    try { JSON.parse(event.body); }
    catch (_) { return reply(400, { error: "Body is not valid JSON" }); }

    try {
      const res = await fetch(binUrl, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          "X-Master-Key": MASTER_KEY,
          "X-Bin-Versioning": "false",
        },
        body: event.body,
      });
      const body = await res.text();
      return { statusCode: res.status, headers: JSON_HEADERS, body };
    } catch (e) {
      return reply(502, { error: "Upstream PUT failed", detail: String(e && e.message || e) });
    }
  }

  return reply(405, { error: "Method not allowed" });
};
