-- =============================================================================
-- 050_research_data_pipeline.sql
--
-- The central research-data store — the in-house replacement for the
-- "Data Dump → cluster files → Runway / VR / Demand Score" spreadsheet chain
-- that currently feeds the Online Reports and the client slide decks.
--
-- DELIBERATELY ISOLATED. Every object here is namespaced `rdp_` (research data
-- pipeline) and is NEW — nothing in the live site reads it yet. The online
-- reports still read their existing feeds (report_data_cache / the cluster
-- Google Sheets), and the monthly PDF renderer is untouched. So this schema can
-- be created, populated and verified with ZERO risk to the current tools. We
-- only point consumers at it later, once each dataset is proven correct.
--
-- Layered model (staging -> marts), each layer its own trackable table:
--   L0  rdp_sources                         registry of external feeds
--   L1  rdp_regions / rdp_metrics           canonical dimensions (fix name + vocab)
--       rdp_raw_series                      long-format raw time-series (ingest here first)
--   L2  rdp_report_feed                     ~37 regions x report columns (= the 4 cluster files)
--       rdp_vr_forecast / rdp_runway /
--       rdp_demand_score / rdp_civ          regenerated derived marts
--       rdp_runs                            lineage / audit log (auto Update Log)
--
-- Marts store a per-region jsonb `payload` (matching the region_dashboard
-- pattern), so the exact column set lives in data, not DDL — no schema churn as
-- the report shape evolves. Logic lives in versioned calculators (code), run by
-- Data Forge; this file is storage only.
--
-- RLS mirrors region_dashboard / report_data_cache: any authenticated user
-- READS; only writers (dev/admin, via public.is_writer()) WRITE. Run after
-- 001_init.sql (needs public.is_writer()). Re-runnable.
-- =============================================================================

-- ── L0 · sources registry ───────────────────────────────────────────────────
create table if not exists public.rdp_sources (
  key              text primary key,
  label            text not null,
  cadence          text,
  notes            text,
  last_ingested_at timestamptz
);
comment on table public.rdp_sources is 'External data feeds (CoreLogic, SQM, ABS, RBA, Oxford Economics, realestate) + last-ingested marker.';

-- ── L1 · canonical dimensions ───────────────────────────────────────────────
create table if not exists public.rdp_regions (
  slug     text primary key,
  name     text not null,
  state    text,
  cluster  text,                              -- capital | qld | nsw | vicwatas
  aliases  jsonb not null default '{}'::jsonb,-- per-source name variants, e.g. {"clpf":"SYDNEY (NSW)","abs":"SYDNEY, NSW"}
  sort     int
);
comment on table public.rdp_regions is 'Canonical region dimension + per-source alias map — one key, fixes the "SYDNEY (NSW)" / "SYDNEY, NSW" / "Sydney" mismatch once.';

create table if not exists public.rdp_metrics (
  code          text primary key,
  label         text not null,
  unit          text,                         -- money | money_week | pct | count | days | ratio
  category      text,
  property_type char(1)                        -- H | U | null
);
comment on table public.rdp_metrics is 'Controlled metric vocabulary (code, label, unit) so every series is named consistently.';

-- ── L1 · raw time-series (the ingestion target) ─────────────────────────────
create table if not exists public.rdp_raw_series (
  source      text not null,
  region_slug text not null,
  metric      text not null,
  freq        char(1) not null default 'A',   -- A annual | M monthly | Q quarterly
  period      date not null,                   -- annual -> YYYY-01-01, monthly -> YYYY-MM-01
  value       numeric,
  primary key (source, region_slug, metric, freq, period)
);
comment on table public.rdp_raw_series is 'Canonical long-format raw data ("put all the data here first"). One shape absorbs CLPF/CLRent/SQM/Population/Approvals/etc. Source is in the PK so overlapping feeds (e.g. SQM vs CLRent rents) coexist; marts pick the authoritative source.';
create index if not exists rdp_raw_series_metric_period on public.rdp_raw_series (metric, period);
create index if not exists rdp_raw_series_region_metric on public.rdp_raw_series (region_slug, metric);

-- ── L2 · derived marts (regenerated by code) ────────────────────────────────
create table if not exists public.rdp_report_feed (
  region_slug  text primary key,
  cluster      text,
  payload      jsonb       not null,           -- the report-ready columns (reproduces the 81-col cluster tab)
  source_month text,
  computed_at  timestamptz not null default now(),
  computed_by  uuid        references auth.users
);
comment on table public.rdp_report_feed is 'Regenerated per-region report data (= the 4 cluster files unified). Cluster-compat views expose the capital/qld/nsw/vicwatas splits.';
create index if not exists rdp_report_feed_cluster on public.rdp_report_feed (cluster);

create table if not exists public.rdp_vr_forecast (
  region_slug  text primary key,
  payload      jsonb       not null,
  source_month text,
  computed_at  timestamptz not null default now(),
  computed_by  uuid        references auth.users
);
comment on table public.rdp_vr_forecast is 'Regenerated vacancy-rate forecast per region (replaces VR Projections workbook).';

create table if not exists public.rdp_runway (
  region_slug  text primary key,
  payload      jsonb       not null,
  source_month text,
  computed_at  timestamptz not null default now(),
  computed_by  uuid        references auth.users
);
comment on table public.rdp_runway is 'Regenerated runway data — wage growth + price-forecast scenarios (replaces Runway Workbook).';

create table if not exists public.rdp_demand_score (
  region_slug  text primary key,
  payload      jsonb       not null,
  source_month text,
  computed_at  timestamptz not null default now(),
  computed_by  uuid        references auth.users
);
comment on table public.rdp_demand_score is 'Regenerated demand score per region (replaces the Demand Score sheets).';

create table if not exists public.rdp_civ (
  region_slug  text primary key,
  payload      jsonb       not null,
  source_month text,
  computed_at  timestamptz not null default now(),
  computed_by  uuid        references auth.users
);
comment on table public.rdp_civ is 'Current investment value per region (current price / rent / yield); "current" = latest period, no hardcoded row.';

-- ── lineage / audit log (auto replacement for the manual Update Log) ─────────
create table if not exists public.rdp_runs (
  id           bigint generated by default as identity primary key,
  dataset      text not null,                  -- raw | report_feed | vr_forecast | runway | demand_score | civ
  source_month text,
  row_count    int,
  status       text,                           -- ok | error
  notes        text,
  run_by       uuid references auth.users,
  run_at       timestamptz not null default now()
);
comment on table public.rdp_runs is 'Every ingestion/regeneration logged automatically (dataset, source month, rows, who, when).';
create index if not exists rdp_runs_dataset_run_at on public.rdp_runs (dataset, run_at desc);

-- ── RLS: authenticated read; writers (dev/admin) write ──────────────────────
do $$
declare t text;
begin
  foreach t in array array[
    'rdp_sources','rdp_regions','rdp_metrics','rdp_raw_series',
    'rdp_report_feed','rdp_vr_forecast','rdp_runway','rdp_demand_score','rdp_civ','rdp_runs'
  ] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "%s_sel" on public.%I', t, t);
    execute format('create policy "%s_sel" on public.%I for select to authenticated using (true)', t, t);
    execute format('drop policy if exists "%s_ins" on public.%I', t, t);
    execute format('create policy "%s_ins" on public.%I for insert to authenticated with check (public.is_writer())', t, t);
    execute format('drop policy if exists "%s_upd" on public.%I', t, t);
    execute format('create policy "%s_upd" on public.%I for update to authenticated using (public.is_writer()) with check (public.is_writer())', t, t);
    execute format('drop policy if exists "%s_del" on public.%I', t, t);
    execute format('create policy "%s_del" on public.%I for delete to authenticated using (public.is_writer())', t, t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
  end loop;
end $$;
grant usage, select on all sequences in schema public to authenticated;  -- rdp_runs identity

-- ── cluster-compatibility views (so consumers can read the old 4-way split) ──
-- security_invoker => RLS of the base table still applies through the view.
create or replace view public.rdp_report_feed_capital   with (security_invoker=on) as select * from public.rdp_report_feed where cluster = 'capital';
create or replace view public.rdp_report_feed_qld       with (security_invoker=on) as select * from public.rdp_report_feed where cluster = 'qld';
create or replace view public.rdp_report_feed_nsw       with (security_invoker=on) as select * from public.rdp_report_feed where cluster = 'nsw';
create or replace view public.rdp_report_feed_vicwatas  with (security_invoker=on) as select * from public.rdp_report_feed where cluster = 'vicwatas';
grant select on public.rdp_report_feed_capital, public.rdp_report_feed_qld,
                public.rdp_report_feed_nsw, public.rdp_report_feed_vicwatas to authenticated;

-- ── seed: sources ───────────────────────────────────────────────────────────
insert into public.rdp_sources (key, label, cadence, notes) values
  ('corelogic','CoreLogic / Pricefinder','monthly','Median price, sales, days on market'),
  ('sqm','SQM Research','monthly','Vacancy rate, stock on market, rents'),
  ('abs','ABS','periodic','Population, migration, approvals, age pyramid'),
  ('rba','RBA','monthly','Cash rate, bank/variable rate'),
  ('oxford','Oxford Economics','annual','Dwelling commencements'),
  ('rea','realestate.com.au','monthly','Listing counts (manual lookup)')
on conflict (key) do nothing;

-- ── seed: canonical regions (the ~37 report regions + national) ──────────────
insert into public.rdp_regions (slug, name, state, cluster, sort) values
  ('australia','Australia',null,'capital',1),
  ('sydney','Sydney','NSW','capital',2),
  ('melbourne','Melbourne','VIC','capital',3),
  ('brisbane','Brisbane','QLD','capital',4),
  ('perth','Perth','WA','capital',5),
  ('adelaide','Adelaide','SA','capital',6),
  ('canberra','Canberra','ACT','capital',7),
  ('hobart','Hobart','TAS','capital',8),
  ('darwin','Darwin','NT','capital',9),
  ('mackay','Mackay','QLD','qld',20),
  ('bundaberg','Bundaberg','QLD','qld',21),
  ('ipswich','Ipswich','QLD','qld',22),
  ('rockhampton','Rockhampton','QLD','qld',23),
  ('gladstone','Gladstone','QLD','qld',24),
  ('cairns','Cairns','QLD','qld',25),
  ('townsville','Townsville','QLD','qld',26),
  ('sunshine-coast','Sunshine Coast','QLD','qld',27),
  ('toowoomba','Toowoomba','QLD','qld',28),
  ('gold-coast','Gold Coast','QLD','qld',29),
  ('albury','Albury','NSW','nsw',40),
  ('central-coast','Central Coast','NSW','nsw',41),
  ('coffs-harbour','Coffs Harbour','NSW','nsw',42),
  ('newcastle','Newcastle','NSW','nsw',43),
  ('orange','Orange','NSW','nsw',44),
  ('port-macquarie','Port Macquarie','NSW','nsw',45),
  ('tamworth','Tamworth','NSW','nsw',46),
  ('wagga-wagga','Wagga Wagga','NSW','nsw',47),
  ('wollongong','Wollongong','NSW','nsw',48),
  ('dubbo','Dubbo','NSW','nsw',49),
  ('ballarat','Ballarat','VIC','vicwatas',60),
  ('bendigo','Bendigo','VIC','vicwatas',61),
  ('geelong','Geelong','VIC','vicwatas',62),
  ('wodonga','Wodonga','VIC','vicwatas',63),
  ('mildura','Mildura','VIC','vicwatas',64),
  ('mandurah','Mandurah','WA','vicwatas',65),
  ('rockingham','Rockingham','WA','vicwatas',66),
  ('bunbury','Bunbury','WA','vicwatas',67),
  ('launceston','Launceston','TAS','vicwatas',68)
on conflict (slug) do nothing;

-- ── seed: core metric vocabulary ────────────────────────────────────────────
insert into public.rdp_metrics (code, label, unit, category, property_type) values
  ('mp_h','Median Price — House','money','price','H'),
  ('mp_u','Median Price — Unit','money','price','U'),
  ('sales_h','Sales — House','count','sales','H'),
  ('sales_u','Sales — Unit','count','sales','U'),
  ('adom_h','Avg Days on Market — House','days','market','H'),
  ('adom_u','Avg Days on Market — Unit','days','market','U'),
  ('rent_h','Advertised Rent — House','money_week','rent','H'),
  ('rent_u','Advertised Rent — Unit','money_week','rent','U'),
  ('som_h','Stock on Market — House','count','market','H'),
  ('som_u','Stock on Market — Unit','count','market','U'),
  ('vacancy_rate','Vacancy Rate','pct','rent',null),
  ('population','Population','count','demographics',null),
  ('natural_increase','Natural Increase','count','demographics',null),
  ('nom','Net Overseas Migration','count','demographics',null),
  ('nim','Net Internal Migration','count','demographics',null),
  ('approvals_h','Building Approvals — House','count','supply','H'),
  ('approvals_u','Building Approvals — Unit','count','supply','U'),
  ('dwellings','Dwellings','count','supply',null),
  ('unemployment','Unemployment Rate','pct','economy',null),
  ('cash_rate','Cash Rate','pct','macro',null),
  ('bank_rate','Bank / Variable Rate','pct','macro',null),
  ('inflation','Inflation Rate','pct','macro',null),
  ('median_income','Median Weekly Income','money_week','economy',null)
on conflict (code) do nothing;
